In [1]:
# label encoding
# target(label) 에만 적용해야 한다

In [3]:
targets = ['청바지', '치마', '청바지', '원피스', '청바지', '치마', '치마', '청바지', '원피스']
# 기본적으로는 그대로는 모델에 넣을 수 없고, 숫자 형태로 바꿔주어야 한다. (encoding)

In [4]:
from sklearn.preprocessing import LabelEncoder

lbl_encoder = LabelEncoder()

In [5]:
# 전처리라는 것은 데이터를 변형(transformation) 시키는 작업
# 데이터에 변형을 일으키는 class 를 Transformer 라고 한다. (Transformer algorigthm 과는 다르다!)

In [7]:
lbl_encoder.fit(targets)
#target 데이터를 laber encoder 에 적용

LabelEncoder()

In [10]:
lbl_encoder.classes_
# 데이터 변형의 근거 => 어떤 class 들이 있는지?

array(['원피스', '청바지', '치마'], dtype='<U3')

In [13]:
encoded_targets = lbl_encoder.transform(targets)
encoded_targets

array([1, 2, 1, 0, 1, 2, 2, 1, 0])

In [14]:
## one hot encoding (매우 중요!)

In [15]:
from sklearn.preprocessing import OneHotEncoder

ohe_encoder = OneHotEncoder()

In [17]:
# LabelEncoder 는 target 을 바꿔주는 역할을 하기 때문에 1차원 배열로 데이터가 들어가면 된다.
# OneHotEncoder 는 feature 에 적용. feature 는 항상 2차원 배열의 형식

# 1차원 배열을 2차원 배열로 변형 => vector to matrix
# R^N -> R^(Nx1)

In [23]:
import numpy as np

items_arr = np.array(targets).reshape(-1, 1) #2d arr 형태로 전환
items_arr

array([['청바지'],
       ['치마'],
       ['청바지'],
       ['원피스'],
       ['청바지'],
       ['치마'],
       ['치마'],
       ['청바지'],
       ['원피스']], dtype='<U3')

In [24]:
ohe_encoder.fit(items_arr)
ohe_datas = ohe_encoder.transform(items_arr)

ohe_datas

<9x3 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [25]:
#압축된 희소행렬 format => 1이 있는 좌표 정보
print(ohe_datas)

  (0, 1)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (3, 0)	1.0
  (4, 1)	1.0
  (5, 2)	1.0
  (6, 2)	1.0
  (7, 1)	1.0
  (8, 0)	1.0


In [26]:
# feature scaling

In [27]:
# MinMaxScaling (정규화) => 0과 1 사이로 정규화 시켜주는 transformer

In [28]:
import pandas as pd

movie_score = pd.DataFrame({
    "naver":[0, 2, 4, 6, 8],
    "netflix":[1, 2, 3, 4, 5]
})

movie_score

naver  netflix
0      0        1
1      2        2
2      4        3
3      6        4
4      8        5

In [29]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()

In [30]:
min_max_scaler.fit(movie_score)

MinMaxScaler()

In [32]:
movie_score_scaled = min_max_scaler.transform(movie_score)
movie_score_scaled

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])

In [33]:
# StandardScaling (표준화)
# 데이터 정리
# 흩트러진 데이터를 원점 기준으로 정리
# 평균을 0, 표준편차를 1로 변환

In [34]:
data1 = np.array([100, 110, 120, 130, 140])
data2 = np.array([0, 1, 2, 3, 4])

In [35]:
data1.mean(), data2.mean()

(120.0, 2.0)

In [36]:
data1.std(), data2.std()

(14.142135623730951, 1.4142135623730951)

In [38]:
from sklearn.preprocessing import StandardScaler

std_scaler1 = StandardScaler()
std_scaler2 = StandardScaler()

In [39]:
std_scaler1.fit(data1.reshape(-1,1))
std_scaler2.fit(data2.reshape(-1,1))

StandardScaler()

In [43]:
data1_scaled = std_scaler1.transform(data1.reshape(-1, 1))
data2_scaled = std_scaler2.transform(data2.reshape(-1, 1))

In [44]:
print(data1_scaled)
print()
print(data2_scaled)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [45]:
data1_scaled.mean(), data2_scaled.mean()

(0.0, 0.0)

In [46]:
data1_scaled.std(), data2_scaled.std()

(0.9999999999999999, 0.9999999999999999)