# 데이터 전처리

## 레이블 인코딩 (Label Encoding)

In [1]:
# Target(Label)에만 적용해야 한다.
targets = ["청바지", "치마", "청바지", "원피스", "청바지", "치마", "치마", "청바지", "원피스"]

In [2]:
from sklearn.preprocessing import LabelEncoder

lbl_encoder = LabelEncoder()

전처리라는 것은 데이터를 변형(Transformation)시키는 작업. 데이터의 변형을 일으키는 클래스를 **Transformer**(알고리즘이 아님!!)

In [4]:
lbl_encoder.fit(targets)

LabelEncoder()

In [5]:
lbl_encoder.classes_

array(['원피스', '청바지', '치마'], dtype='<U3')

In [6]:
encoded_targets = lbl_encoder.transform(targets)
encoded_targets

array([1, 2, 1, 0, 1, 2, 2, 1, 0])

In [7]:
targets

['청바지', '치마', '청바지', '원피스', '청바지', '치마', '치마', '청바지', '원피스']

## One Hot Encoding⭐

In [8]:
from sklearn.preprocessing import OneHotEncoder

ohe_encoder = OneHotEncoder()

In [11]:
# LabelEncoder는 target을 바꿔주는 역할을 하기 때문에 1차원 배열로 데이터가 들어가면 됩니다.
# OneHotEncoder는 Feature에 적용된다. Feature는 항상 2차원 배열의 형식으로 들어가야 한다.

# 1차원 배열을 2차원 배열로 변형
# Vector를 Matrix로 변환
# R^N -> R^Nx1

import numpy as np

items_arr = np.array(targets).reshape(-1, 1)
items_arr

array([['청바지'],
       ['치마'],
       ['청바지'],
       ['원피스'],
       ['청바지'],
       ['치마'],
       ['치마'],
       ['청바지'],
       ['원피스']], dtype='<U3')

In [12]:
ohe_encoder.fit(items_arr)
ohe_datas = ohe_encoder.transform(items_arr)

ohe_datas

<9x3 sparse matrix of type '<class 'numpy.float64'>'
	with 9 stored elements in Compressed Sparse Row format>

In [13]:
# 압축된 희소행렬 포맷
print(ohe_datas)

  (0, 1)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (3, 0)	1.0
  (4, 1)	1.0
  (5, 2)	1.0
  (6, 2)	1.0
  (7, 1)	1.0
  (8, 0)	1.0


In [14]:
# 압축된 희소행렬 형태를 풀어서 표현
ohe_datas.toarray()

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

# Feature Scaling

## MinMaxScaling(정규화)
- 0 ~ 1 사이로 정규화 시켜주는 Transformer

In [15]:
import pandas as pd

movie_score = pd.DataFrame({
    "naver":[0, 2, 4, 6, 8],
    "netflix":[1, 2, 3, 4, 5]
})

movie_score

naver  netflix
0      0        1
1      2        2
2      4        3
3      6        4
4      8        5

In [16]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()

In [17]:
min_max_scaler.fit(movie_score) # 데이터의 최댓값과 최솟값을 찾는다.

MinMaxScaler()

In [18]:
movie_score_scaled = min_max_scaler.transform(movie_score)
movie_score_scaled

array([[0.  , 0.  ],
       [0.25, 0.25],
       [0.5 , 0.5 ],
       [0.75, 0.75],
       [1.  , 1.  ]])

## StandardScaling (표준화)
- 데이터를 정리한다는 개념
- 흩트러진 데이터를 원점 기준으로 정리
- 평균을 0, 표준편차를 1로 변환

In [19]:
data1 = np.array([100, 110, 120, 130, 140])
data2 = np.array([0, 1, 2, 3, 4])

In [20]:
# 각 데이터의 평균
data1.mean(), data2.mean()

(120.0, 2.0)

In [21]:
# 각 데이터의 표준편차
data1.std(), data2.std()

(14.142135623730951, 1.4142135623730951)

In [23]:
from sklearn.preprocessing import StandardScaler

std_scaler1 = StandardScaler()
std_scaler2 = StandardScaler()

In [24]:
std_scaler1.fit(data1.reshape(-1, 1))
std_scaler2.fit(data2.reshape(-1, 1))

StandardScaler()

In [25]:
data1_scaled = std_scaler1.transform(data1.reshape(-1, 1))
data2_scaled = std_scaler2.transform(data2.reshape(-1, 1))

In [26]:
print(data1_scaled)
print()
print(data2_scaled)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [27]:
data1_scaled.mean(), data2_scaled.mean()

(0.0, 0.0)

In [28]:
data1_scaled.std(), data2_scaled.std()

(0.9999999999999999, 0.9999999999999999)